// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroScolastico.Data;

#nullable disable

namespace RegistroScolastico.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250628203221_Creazione")]
    partial class Creazione
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocenteCollegio", b =>
                {
                    b.Property<int>("CollegioDocentiId")
                        .HasColumnType("int");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.HasKey("CollegioDocentiId", "DocenteId");

                    b.HasIndex("DocenteId");

                    b.ToTable("DocenteCollegio");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Anno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Anni");
                });

            modelBuilder.Entity("RegistroScolastico.Models.AnnoFormativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AnniFormativi");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnoFormativoId")
                        .HasColumnType("int");

                    b.Property<int>("AnnoId")
                        .HasColumnType("int");

                    b.Property<int?>("CollegioDocentiId")
                        .HasColumnType("int");

                    b.Property<int>("CorsoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("SezioneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnnoFormativoId");

                    b.HasIndex("CollegioDocentiId");

                    b.HasIndex("CorsoId");

                    b.HasIndex("SezioneId");

                    b.HasIndex("AnnoId", "SezioneId", "AnnoFormativoId", "CorsoId")
                        .IsUnique();

                    b.ToTable("Classi");
                });

            modelBuilder.Entity("RegistroScolastico.Models.CollegioDocenti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CollegiDocenti");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Colloquio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudenteId");

                    b.ToTable("Colloqui");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ColloquioAmbito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColloquioId")
                        .HasColumnType("int");

                    b.Property<string>("Competenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ColloquioId");

                    b.ToTable("ColloquiAmbiti");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ColloquioCriterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmbitoId")
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PesoRelativo")
                        .HasColumnType("int");

                    b.Property<int>("Voto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmbitoId");

                    b.ToTable("ColloquiCriteri");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Corso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Docente", b =>
                {
                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("UtenteId");

                    b.ToTable("Docenti");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Luogo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatoreId");

                    b.ToTable("Eventi");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Materie");
                });

            modelBuilder.Entity("RegistroScolastico.Models.MateriaClasse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClasseId")
                        .HasColumnType("int");

                    b.Property<int?>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("MateriaId");

                    b.ToTable("MaterieClassi");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Moduli");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ModuloMateria", b =>
                {
                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("ModuloId", "MateriaId");

                    b.HasIndex("MateriaId");

                    b.ToTable("ModuliMaterie");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Profilo", b =>
                {
                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InfoAggiuntive")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UtenteId");

                    b.HasIndex("CodiceFiscale")
                        .IsUnique();

                    b.ToTable("Profili");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaMultidisciplinare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudenteId");

                    b.ToTable("ProveMultidisciplinari");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaMultidisciplinareSezione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Competenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumDomande")
                        .HasColumnType("int");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("ProvaMultidisciplinareId")
                        .HasColumnType("int");

                    b.Property<int>("Punteggio")
                        .HasColumnType("int");

                    b.Property<int>("PuntiPerDomanda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvaMultidisciplinareId");

                    b.ToTable("ProveMultidisciplinariSezioni");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleCompitoTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("ProveSituazionaliCompitiTemplate");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleIndicatoreTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompitoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("PunteggioMax")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompitoId");

                    b.ToTable("ProveSituazionaliIndicatoriTemplate");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClasseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId")
                        .IsUnique();

                    b.ToTable("ProveSituazionaliTemplate");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleValutazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompitoId")
                        .HasColumnType("int");

                    b.Property<int>("IndicatoreId")
                        .HasColumnType("int");

                    b.Property<int>("Livello")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompitoId");

                    b.HasIndex("IndicatoreId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("StudenteId", "CompitoId")
                        .IsUnique();

                    b.ToTable("ProveSituazionaliValutazioni");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Sezione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Sezioni");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Studente", b =>
                {
                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.Property<int>("ClasseId")
                        .HasColumnType("int");

                    b.HasKey("UtenteId");

                    b.HasIndex("ClasseId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataUltimoAccesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ruolo")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ValutazioneFinale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCalcolo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.Property<int>("VotoAmmissione")
                        .HasColumnType("int");

                    b.Property<int>("VotoFinale")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("StudenteId");

                    b.ToTable("ValutazioniFinali");
                });

            modelBuilder.Entity("DocenteCollegio", b =>
                {
                    b.HasOne("RegistroScolastico.Models.CollegioDocenti", null)
                        .WithMany()
                        .HasForeignKey("CollegioDocentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroScolastico.Models.Docente", null)
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroScolastico.Models.Classe", b =>
                {
                    b.HasOne("RegistroScolastico.Models.AnnoFormativo", "AnnoFormativo")
                        .WithMany("Classi")
                        .HasForeignKey("AnnoFormativoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroScolastico.Models.Anno", "Anno")
                        .WithMany()
                        .HasForeignKey("AnnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroScolastico.Models.CollegioDocenti", "CollegioDocenti")
                        .WithMany("Classi")
                        .HasForeignKey("CollegioDocentiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RegistroScolastico.Models.Corso", "Corso")
                        .WithMany("Classi")
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroScolastico.Models.Sezione", "Sezione")
                        .WithMany()
                        .HasForeignKey("SezioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anno");

                    b.Navigation("AnnoFormativo");

                    b.Navigation("CollegioDocenti");

                    b.Navigation("Corso");

                    b.Navigation("Sezione");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Colloquio", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Studente", "Studente")
                        .WithMany("Colloqui")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ColloquioAmbito", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Colloquio", "Colloquio")
                        .WithMany("Ambiti")
                        .HasForeignKey("ColloquioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colloquio");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ColloquioCriterio", b =>
                {
                    b.HasOne("RegistroScolastico.Models.ColloquioAmbito", "Ambito")
                        .WithMany("Criteri")
                        .HasForeignKey("AmbitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambito");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Docente", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Evento", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Utente", "Creatore")
                        .WithMany()
                        .HasForeignKey("CreatoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creatore");
                });

            modelBuilder.Entity("RegistroScolastico.Models.MateriaClasse", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Classe", "Classe")
                        .WithMany("MaterieClassi")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RegistroScolastico.Models.Docente", "Docente")
                        .WithMany("MaterieInsegnate")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RegistroScolastico.Models.Materia", "Materia")
                        .WithMany("Classi")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ModuloMateria", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Materia", "Materia")
                        .WithMany("Moduli")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroScolastico.Models.Modulo", "Modulo")
                        .WithMany("Materie")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Profilo", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Utente", "Utente")
                        .WithOne("Profilo")
                        .HasForeignKey("RegistroScolastico.Models.Profilo", "UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaMultidisciplinare", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Studente", "Studente")
                        .WithMany("ProveMultidisciplinari")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaMultidisciplinareSezione", b =>
                {
                    b.HasOne("RegistroScolastico.Models.ProvaMultidisciplinare", "ProvaMultidisciplinare")
                        .WithMany("Sezioni")
                        .HasForeignKey("ProvaMultidisciplinareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProvaMultidisciplinare");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleCompitoTemplate", b =>
                {
                    b.HasOne("RegistroScolastico.Models.ProvaSituazionaleTemplate", "Template")
                        .WithMany("Compiti")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleIndicatoreTemplate", b =>
                {
                    b.HasOne("RegistroScolastico.Models.ProvaSituazionaleCompitoTemplate", "Compito")
                        .WithMany("Indicatori")
                        .HasForeignKey("CompitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compito");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleTemplate", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Classe", "Classe")
                        .WithOne()
                        .HasForeignKey("RegistroScolastico.Models.ProvaSituazionaleTemplate", "ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleValutazione", b =>
                {
                    b.HasOne("RegistroScolastico.Models.ProvaSituazionaleCompitoTemplate", "Compito")
                        .WithMany()
                        .HasForeignKey("CompitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroScolastico.Models.ProvaSituazionaleIndicatoreTemplate", "Indicatore")
                        .WithMany()
                        .HasForeignKey("IndicatoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroScolastico.Models.Studente", "Studente")
                        .WithMany("ProveSituazionaliValutazioni")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroScolastico.Models.ProvaSituazionaleTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compito");

                    b.Navigation("Indicatore");

                    b.Navigation("Studente");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Studente", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Classe", "Classe")
                        .WithMany("Studenti")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroScolastico.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ValutazioneFinale", b =>
                {
                    b.HasOne("RegistroScolastico.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId");

                    b.HasOne("RegistroScolastico.Models.Studente", "Studente")
                        .WithMany("ValutazioniFinali")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("RegistroScolastico.Models.AnnoFormativo", b =>
                {
                    b.Navigation("Classi");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Classe", b =>
                {
                    b.Navigation("MaterieClassi");

                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("RegistroScolastico.Models.CollegioDocenti", b =>
                {
                    b.Navigation("Classi");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Colloquio", b =>
                {
                    b.Navigation("Ambiti");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ColloquioAmbito", b =>
                {
                    b.Navigation("Criteri");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Corso", b =>
                {
                    b.Navigation("Classi");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Docente", b =>
                {
                    b.Navigation("MaterieInsegnate");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Materia", b =>
                {
                    b.Navigation("Classi");

                    b.Navigation("Moduli");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Modulo", b =>
                {
                    b.Navigation("Materie");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaMultidisciplinare", b =>
                {
                    b.Navigation("Sezioni");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleCompitoTemplate", b =>
                {
                    b.Navigation("Indicatori");
                });

            modelBuilder.Entity("RegistroScolastico.Models.ProvaSituazionaleTemplate", b =>
                {
                    b.Navigation("Compiti");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Studente", b =>
                {
                    b.Navigation("Colloqui");

                    b.Navigation("ProveMultidisciplinari");

                    b.Navigation("ProveSituazionaliValutazioni");

                    b.Navigation("ValutazioniFinali");
                });

            modelBuilder.Entity("RegistroScolastico.Models.Utente", b =>
                {
                    b.Navigation("Profilo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
